### PR TITLE
fix: silent error when database connection fails (#74)

### LINKED ISSUE #74: Database module fails when connection to the mongo cluster can't be established
Noticed this while testing in my environment; My Atlas cluster was in a paused state and didn't notice, the Lambdas were failing but nothing showed in the logs.

I suggest adding a catch statement in the database constructor to avoid having an instance of that class in an invalid state.

### PR DESCRIPTION
**Pull request by wperron**
Adds visibility in the Lambda logs when connection to mongodb fails, Fixes #74 

Note, this is a big ol' patch of duct tape to give a little more visibility that there's an issue with the database connection. Ultimately, the issue comes from the underlying mongodb library that just assigns undefined to the clientId instead of raising an error. A long term fix would require either submitting a change to the mongo lib, or use a different one

### CODE REVIEW

File: utils/database.ts [hunk 1]
```diff
@@ -51,6 +51,9 @@ export class Database {
 
   constructor(mongoUri: string) {
     this.mongo.connectWithUri(mongoUri);
+    if (this.mongo.clientId === null || this.mongo.clientId === undefined) {
+      throw new Error("Could not connect to database.");
```
Comment (ry) [inline utils/database.ts:55]: Maybe just !this.mongo.clientId

Comment (lucacasonato) [reply utils/database.ts:55]: The client id can be 0 I think - so this seems safer.

Comment (wperron) [reply utils/database.ts:55]: was about to say the same thing, I did some tests and `!this.mongo.clientId` throws even though it shouldn't. Just doing some tests to confirm rn

Comment (wperron) [reply utils/database.ts:55]: Yup, I modified my lambda function to print the client it and it is indeed `0` on success (I'm guessing it acts a as sort of index when multiple connections are established?)

**Review by lucacasonato — APPROVED** [review]
LGTM - thanks William
